### ISSUE TITLE
config.js template missing?

### ISSUE THREAD

**Issue by beniwtv** [mccraveiro/mongoose-migration#7]
Hi, 

just installed via npm, and I get:

```
$ migrate init
prompt: Enter migrations directory:  (migrations) 
prompt: Enter mongo connection string:  [redacted]
readline.js:924
            throw err;
            ^

Error: ENOENT: no such file or directory, open '/vagrant/node_modules/mongoose-migration/template/config.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /vagrant/node_modules/mongoose-migration/bin/migrate.js:109:19
    at /vagrant/node_modules/prompt/lib/prompt.js:316:32
    at /vagrant/node_modules/utile/node_modules/async/lib/async.js:142:25
    at assembler (/vagrant/node_modules/prompt/lib/prompt.js:313:9)
    at /vagrant/node_modules/prompt/lib/prompt.js:322:32
    at /vagrant/node_modules/prompt/lib/prompt.js:597:5
    at Interface.onLine (/vagrant/node_modules/read/lib/read.js:111:5)

```

Any ideas? The config.js file is not in the templates path, only migration.js

Thanks,
Benedikt

**Comment by mccraveiro** [comment]
I reverted the pull request that introduced bugs. The package should be working now. 
I am sorry it took so long.
